=== tcm24twg10/-tcm24twg10/src/combos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">


  <xs:element name="combos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="combo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="destino" type="xs:string"/>
              <xs:element name="descricao" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== tcm24twg10/-tcm24twg10/src/combos.xml
<?xml version="1.0" encoding="UTF-8"?>
<combos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="combos.xsd">
    <combo>
        <titulo>Gula + Luxúria</titulo>
        <destino>Roma</destino>
        <descricao>Degusta a culinária italiana e desfruta do charme e romance da cidade.</descricao>
    </combo>
    <combo>
        <titulo>Avareza + Vaidade</titulo>
        <destino>Dubai</destino>
        <descricao>Explora as compras luxuosas e as atrações deslumbrantes da cidade.</descricao>
    </combo>
    <combo>
        <titulo>Ira + Preguiça</titulo>
        <destino>Islândia</destino>
        <descricao>Sente a força das paisagens vulcânicas e relaxa nas águas quentes da Lagoa Azul.</descricao>
    </combo>
    <combo>
        <titulo>Inveja + Luxúria</titulo>
        <destino>Paris</destino>
        <descricao>Desfruta do glamour parisiense e vive o romance com um toque de elegância.</descricao>
    </combo>
    <combo>
        <titulo>Vaidade + Preguiça</titulo>
        <destino>Santorini</destino>
        <descricao>Admira o pôr do sol perfeito e relaxa nas praias de areia vulcânica.</descricao>
    </combo>
    <combo>
        <titulo>Avareza + Inveja</titulo>
        <destino>Mônaco</destino>
        <descricao>Vive o glamour dos casinos e os iates de luxo no coração da Riviera Francesa.</descricao>
    </combo>
    <combo>
        <titulo>Gula + Preguiça</titulo>
        <destino>Toscana</destino>
        <descricao>Saboreia os vinhos e pratos típicos enquanto relaxas nas colinas ensolaradas.</descricao>
    </combo>
    <combo>
        <titulo>Ira + Vaidade</titulo>
        <destino>Egito</destino>
        <descricao>Experimenta a força do deserto e admira a grandeza das pirâmides.</descricao>
    </combo>
</combos>
